# Generated by Django 2.0.4 on 2018-05-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[('', 'Wybierz kategorię'), ('sport', 'Sport'), ('muzyka', 'Muzyka'), ('nauka', 'Nauka'), ('sztuka', 'Sztuka'), ('gry', 'Gry'), ('pozostałe', 'Pozostałe')], max_length=9)),
                ('city', models.CharField(max_length=30)),
                ('city_area', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField()),
                ('min_number_of_participants', models.PositiveSmallIntegerField(default=2)),
                ('max_number_of_participants', models.PositiveSmallIntegerField(default=2)),
                ('description', models.CharField(max_length=280)),
            ],
        ),
    ]
