# Generated by Django 2.0.4 on 2018-05-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('sport', 'Sport'), ('muzyka', 'Muzyka'), ('nauka', 'Nauka'), ('sztuka', 'Sztuka'), ('gry', 'Gry'), ('pozostałe', 'Pozostałe')], max_length=9),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_number_of_participants',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_number_of_participants',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
