# Generated by Django 2.0.4 on 2018-05-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180504_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('sport', 'Sport'), ('muzyka', 'Muzyka'), ('nauka', 'Nauka'), ('sztuka', 'Sztuka'), ('gry', 'Gry'), ('pozostałe', 'Pozostałe')], default='sport', max_length=9),
        ),
    ]
