# Generated by Django 2.0.4 on 2018-05-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180504_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_number_of_participants',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_number_of_participants',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
