# Generated by Django 2.0.4 on 2018-05-07 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180507_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(error_messages={'blank': 'Wpisz miasto, w którym odbędzie się spotkanie'}, max_length=30, validators=[django.core.validators.RegexValidator(message='Wpisz poprawną nazwę miasta', regex='^[a-zA-ZąćęłńóśźżĄĘŁŃÓŚŹŻ.\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='city_area',
            field=models.CharField(blank=True, help_text='Możesz wpisać np. nazwę dzielnicy, osiedla, ulicy', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(error_messages={'blank': 'Ustal termin spotkania'}),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message='Tag może składać się z liter oraz liczb', regex='^[a-zA-ZąćęłńóśźżĄĘŁŃÓŚŹŻ.\\s]+$')]),
        ),
    ]
