# Generated by Django 2.0.4 on 2018-05-07 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20180507_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='min_number_of_participants',
            field=models.PositiveSmallIntegerField(default=2, error_messages={'invalid': 'W spotkaniu może brać udział od 2 do 15 uczestników'}, help_text='Możesz podać minimalną liczbę uczestników, aby spotkanie mogło się odbyć', validators=[django.core.validators.MinValueValidator(2, message='W spotkaniu muszą uczestniczyć conajmniej 2 uczestnicy'), django.core.validators.MaxValueValidator(15, message='W spotkaniu może uczesniczyć maksymalnie 15 uczestników')]),
        ),
    ]
