# Generated by Django 2.0.4 on 2018-05-20 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20180514_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
