# Generated by Django 2.0.4 on 2018-05-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20180520_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tagi mogą ułatwić odnalezienie Twojego spotkania (maks. 5)', null=True, to='events.Tag'),
        ),
    ]
