# Generated by Django 2.0.4 on 2018-05-24 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20180523_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='min_number_of_participants',
            field=models.PositiveSmallIntegerField(blank=True, error_messages={'invalid': 'W spotkaniu może wziąć udział od 2 do 16 uczestników.'}, help_text='Możesz określić minimalną liczbę uczestników, aby spotkanie mogło się odbyć.', null=True, validators=[django.core.validators.MinValueValidator(2, message='W spotkaniu muszą uczestniczyć conajmniej 2 uczestnicy.'), django.core.validators.MaxValueValidator(16, message='W spotkaniu może uczesniczyć maksymalnie 16 uczestników.')]),
        ),
    ]
