# Generated by Django 2.0.5 on 2018-06-11 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20180527_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(error_messages={'blank': 'Wpisz nazwę miasta, w którym odbędzie się spotkanie.'}, max_length=30, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Wpisz poprawną nazwę miasta.', regex='^[a-zA-ZąćęłńóśźżĄĘŁŃÓŚŹŻ.\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='city_area',
            field=models.CharField(blank=True, help_text='Możesz wpisać nazwę ulicy, dzielnicy, osiedla itp.', max_length=30, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
