# Generated by Django 2.0.4 on 2018-05-15 15:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('city', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Wpisz poprawną nazwę miasta', regex='^[a-zA-ZąćęłńóśźżĄĘŁŃÓŚŹŻ.\\s]+$')])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Mężczyzna'), ('F', 'Kobieta')], max_length=1)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
