# Generated by Django 2.0.4 on 2018-05-22 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
