# Generated by Django 2.0.4 on 2018-05-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_violation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='violation',
            field=models.CharField(choices=[('wulgaryzmy', 'Wulgarny język'), ('nękanie', 'Nękanie'), ('nieobecność', 'Nieuczestnictwo w spotkaniu'), ('inny', 'Inny powód')], default='', max_length=255),
        ),
    ]
